rafa= input('Digite algo no teclado: ')
print('O tipo primitivo desse valor é {}'.format(type(rafa)))
print('Só tem espaços? {}'.format(rafa.isspace()))
print('É um número? {}'.format(rafa.isnumeric()))
print('É alfabético? {}'. format(rafa.isalpha()))
print('É alfanumérico? {}'. format(rafa.isalnum()))
print('Está em maiúsculas? {}' .format(rafa.isupper()))
print('Está em minúsculas? {}' . format(rafa.islower()))
print('Está capitalizada? {}' .format(rafa.istitle()))