print('GERADOR DE CRACHÁS')
nome = input('Insira seu nome: ').strip().title()
idade = int(input('Insira sua idade: '))
cidade = input('Insira a cidade que nasceu: ').strip().title()
print('='*22)
print('NOME: {}'.format(nome).center(22))
print('IDADE: {} anos'.format(idade).center(22))
print('CIDADE: {}'.format(cidade).center(22))
print('='*22)
