nome = input('Digite seu nome: ').strip().title()
separado = nome.split()
junto = ''.join(separado)
maiuscula = nome.upper()
minuscula = nome.lower()
num = len(junto)
print('O nome {} em maiúsculo é {}'.format(nome, maiuscula))
print('O nome {} em minúsculo é {}'.format(nome, minuscula))
print('O nome {} tem {} letras'.format(nome, num))
print('As 3 primeiras letras de {} é {}'.format(nome, nome[0:3]))
