num = int(input('Quantos termos deseja mostrar: '))
primeiro = 1
segundo = 0
terceiro = 0
contador = 0
while contador != num:
    contador += 1
    terceiro = segundo + primeiro
    primeiro = segundo
    segundo = terceiro
    print('{} '.format(primeiro), end='')
